#!/bin/bash

BGreen='\033[1;32m'
BRed='\033[1;31m'
NC='\033[0m'
BBlue='\033[1;34m'

function passwd_shadow() {
	echo -e "${BGreen}[+]${NC} Do you see ${BBlue}Write/Read${NC} on ${BGreen}/etc/shadow${NC} ${BBlue}and${NC} ${BGreen}/etc/passwd${NC}"
	ls -lah /etc/passwd | grep 'r\|w' --color=auto
	ls -lah /etc/shadow | grep 'r\|w' --color=auto
	echo
}

function capabilities() {
	echo -e "${BGreen}[+]${NC} ${BBlue}Eye On${NC} ${BRed}Capabilities${NC}"
	command=$(getcap -r / 2>/dev/null)
	echo ${command}
	echo
	echo ${command} | grep 'python\|python3\|perl'

}

function cronjobs() {
	echo -e "${BGreen}[+]${NC} ${BBlue}See some ${BRed}CronJobs${NC} running as${NC} ${BRed}root?${NC}"
	cat /etc/crontab
	echo
}

function keys_ssh() {
	echo -e "${BGreen}[+]${NC} ${BBlue}See some ${BRed}SSH keys?${NC}"
	find / -name id_rsa 2> /dev/null
	echo
}

function dker() {
	echo -e "${BGreen}[+]${NC} ${BBlue}See ${BRed}Docker${NC} in there?"
	id
	id | grep docker --color=auto
	echo
}

function suids() {
	echo -e "${BGreen}[+]${NC} ${BBlue}These Binaries${NC} on ${BRed}GTFObins?${NC}"
	find / -perm -u=s 2> /dev/null
	echo
}

function bash_history() {
	echo -e "${BGreen}[+]${NC} ${BBlue}See something${NC} in ${BRed}Bash History?${NC}"
	cd ~
	cat .bash_history
	echo
}

function config_code() {
	echo -e "${BGreen}[+]${NC} ${BBlue}DB-creds?/compiled-code${NC} intersting ${BRed}.php/.pyc?${NC}"
	find / -name *.php 2> /dev/null &
	find / -name *.pyc 2> /dev/null &
	wait
	echo
}

function hidden_service() {
	echo -e "${BGreen}[+]${NC} ${BBlue}Need some${NC} ${BRed}tunneling?${NC}"
	ss -antlp
	if [ $? -ne 0 ]
	then
		netstat -ano
	fi
	echo
}

function nfs() {
	 echo -e "${BGreen}[+]${NC} ${BBlue}Is there${NC} any ${BRed}NFS?${NC}"
	 cat /etc/exports
	 echo
}

echo -e "\n${BGreen}[+]${NC} Lemon ${BBlue} v(1.0) [Author: ${BRed}z3r0day${NC}${BBlue}] ${BGreen}initialzing${NC} on ${BRed}$(hostname)${NC} at ${BBlue}$(date +%T)${NC}\n"


PS3=$(echo -e "\n${BRed}>${NC}${BGreen}>${NC} ")
echo -e "${BGreen}[+]${NC} ${BBlue}Choose the menu${NC} ${BRed}numbers!${NC}\n"
select answer in "passwd_shadow" "capabilities" "cronjobs" "keys_ssh" "docker" "SUIDs" "bash_history" "config_code" "hidden_services" "NFS_shares" "prompt" "exit"
do
	if [ $answer = "exit" ]
	then
		break
		exit
	fi
		case $answer in
			passwd_shadow)
				passwd_shadow&;;
			capabilities)
				capabilities&;;
			cronjobs)
				cronjobs&;;
			keys_ssh)
				keys_ssh&;;
			docker)
				dker&;;
			SUIDs)
				suids&;;
			bash_history)
				bash_history&;;
			config_code)
				config_code&;;
			hidden_services)
				hidden_service&;;
			NFS_shares)
				nfs&;;
	esac
done

echo -e "\n ${BRed}Exting${NC} with ${BGreen}peace${NC} ${BBlue}:)${NC}"
