#!/bin/bash

# https://github.com/SxNade/Lemon :: Author z3r0day
BGreen='\033[1;32m'
BRed='\033[1;31m'
NC='\033[0m'
BBlue='\033[1;34m'

function passwd_shadow() {
	echo -e "${BGreen}[+]${NC} Do you see ${BBlue}Write/Read${NC} on ${BGreen}/etc/shadow${NC} ${BBlue}and${NC} ${BGreen}/etc/passwd${NC}"
	ls -lah /etc/passwd | grep 'r\|w' --color=auto
	ls -lah /etc/shadow | grep 'r\|w' --color=auto
	echo
}

function whoisthis() {
	echo -e "\n${BBlue}current user:${NC} ${BRed}$(whoami)${NC}"
	echo -e "\n${BBlue}Hostname:${NC} ${BRed}$(hostname)${NC}"
	if [ ${UID} -eq 0 ]
	then
		echo -e "\n${BGreen} You Are Already${NC} ${BRed}root${NC} ${BBlue} Bozzy! Nani?!!${NC}\n"
	fi
	id | grep 'groups\|uid\|root' --color=auto
	echo -e "\n${BGreen}[+]${NC} ${BBlue}Distro!${NC} ${BRed}Kernel exploits??${NC}"
	echo
	cat /etc/os-release
	echo
	cat /proc/version | grep 'Linux\|linux\|Rhel\|debian\|RHEL\|Cent\|ubuntu' --color=auto

	echo -e "\n${BGreen}[+]${NC} ${BBlue}Do we Have${NC} ${BRed}GCC/CC??${NC} or ${BGreen}Cross-compilation${NC}"
	/usr/bin/which gcc | grep gcc --color=auto
	/usr/bin/which cc | grep cc --color=auto

	echo -e "\n${BGreen}[+]${NC} ${BBlue}what${NC} ${BRed}architecture${NC} is ${BGreen}$(hostname)${NC}"
	arch | grep '64\|x86\|i686\|86' --color=auto


	
}
function capabilities() {
	echo -e "${BGreen}[+]${NC} ${BBlue}Eye On${NC} ${BRed}Capabilities${NC}"
	command=$(getcap -r / 2>/dev/null)
	echo ${command}
	echo
	echo ${command} | grep 'python\|python3\|perl'

}

function cronjobs() {
	echo -e "${BGreen}[+]${NC} ${BBlue}See some ${BRed}CronJobs${NC} running as${NC} ${BRed}root?${NC}"
	cat /etc/crontab
	echo
}

function keys_ssh() {
	echo -e "${BGreen}[+]${NC} ${BBlue}See some ${BRed}SSH keys?${NC}"
	find / -name id_rsa 2> /dev/null
	echo
}

function dker() {
	echo -e "${BGreen}[+]${NC} ${BBlue}See ${BRed}Docker${NC} in there?"
	id
	id | grep docker --color=auto
	echo
}

function suids() {
	echo -e "${BGreen}[+]${NC} ${BBlue}These Binaries${NC} on ${BRed}GTFObins?${NC}"
	find / -perm -u=s 2> /dev/null
	echo
}

function bash_history() {
	echo -e "${BGreen}[+]${NC} ${BBlue}See something${NC} in ${BRed}Bash History?${NC}"
	cd ~
	cat .bash_history
	echo
}

function config_code() {
	echo -e "${BGreen}[+]${NC} ${BBlue}DB-creds?/compiled-code${NC} intersting ${BRed}.php/.pyc? :: be paitent this can take time!${NC}"
	find / -name *config*.php 2> /dev/null & 
	find / -name *db*.php 2> /dev/null &
	wait
	echo
}

function hidden_service() {
	echo -e "${BGreen}[+]${NC} ${BBlue}Need some${NC} ${BRed}tunneling?${NC}"
	ss -antlp
	if [ $? -ne 0 ]
	then
		netstat -ano
	fi
	echo
}

function nfs() {
	 echo -e "${BGreen}[+]${NC} ${BBlue}Is there${NC} any ${BRed}NFS?${NC}"
	 cat /etc/exports
	 echo
}

echo -e "\n${BGreen}[+]${NC} Lemon ${BBlue} v(1.0) [Author: ${BRed}z3r0day${NC}${BBlue}] ${BGreen}initialzing${NC} on ${BRed}$(hostname)${NC} at ${BBlue}$(date +%T)${NC}\n"


PS3=$(echo -e "\n${BRed}>${NC}${BGreen}>${NC} ")
echo -e "${BGreen}[+]${NC} ${BBlue}Choose the menu${NC} ${BRed}numbers!${NC}\n"
select answer in "passwd_shadow" "whoisthis" "capabilities" "cronjobs" "keys_ssh" "docker" "SUIDs" "bash_history" "config_code" "hidden_services" "NFS_shares" "exit"
do
	if [ $answer = "exit" ]
	then
		break
		exit
	fi
		case $answer in
			passwd_shadow)
				passwd_shadow&;;
			whoisthis)
				whoisthis&;;
			capabilities)
				capabilities&;;
			cronjobs)
				cronjobs&;;
			keys_ssh)
				keys_ssh&;;
			docker)
				dker&;;
			SUIDs)
				suids&;;
			bash_history)
				bash_history&;;
			config_code)
				config_code&;;
			hidden_services)
				hidden_service&;;
			NFS_shares)
				nfs&;;
	esac
done

echo -e "\n ${BRed}Exting${NC} with ${BGreen}peace${NC} ${BBlue}:)${NC}"

